[book]
title = "The Rust Performance Book for Japanese"
authors = ["Nicholas Nethercote", "Yuki Okushi"]
language = "ja"

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/JohnTitor/perf-book-ja"
site-url = "https://johntitor.github.io/perf-book-ja/"
