name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: |
        yarn
        yarn lint
    - name: Build the book
      run: |
        curl -sL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar zx
        ./mdbook build
